# Form implementation generated from reading ui file 'c:\Users\NB\OneDrive\Documents\KULIAH\Semester 4\RPL\Program\coret2rpl\yg beneran\src\display\DisplayHome\DisplayAdminHome.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.tambahRuteButton = QtWidgets.QPushButton(Dialog)
        self.tambahRuteButton.setGeometry(QtCore.QRect(210, 130, 75, 23))
        self.tambahRuteButton.setObjectName("tambahRuteButton")
        self.signInButton = QtWidgets.QPushButton(Dialog)
        self.signInButton.setGeometry(QtCore.QRect(100, 130, 75, 23))
        self.signInButton.setMouseTracking(False)
        self.signInButton.setObjectName("signInButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tambahRuteButton.setText(_translate("Dialog", "Sign Up"))
        self.signInButton.setText(_translate("Dialog", "Sign In"))
